export const Product = {
  menu: [
    {
      id: 1,
      name: "Hamburger",
      category: "Burgers",
      price: 8.99,
    },
    {
      id: 2,
      name: "Margherita Pizza",
      category: "Pizzas",
      price: 12.99,
    },
    {
      id: 3,
      name: "Caesar Salad",
      category: "Salads",
      price: 7.49,
    },
    {
      id: 4,
      name: "Chicken Alfredo Pasta",
      category: "Pasta",
      price: 10.99,
    },
    {
      id: 5,
      name: "Chocolate Brownie Sundae",
      category: "Desserts",
      price: 6.99,
    },
    {
      id: 6,
      name: "Sushi",
      category: "Japanese",
      price: 15.99,
    },
    {
      id: 7,
      name: "Tacos",
      category: "Mexican",
      price: 9.99,
    },
    {
      id: 8,
      name: "Peking Duck",
      category: "Chinese",
      price: 18.99,
    },
    {
      id: 9,
      name: "Lasagna",
      category: "Italian",
      price: 11.99,
    },
    {
      id: 10,
      name: "Pad Thai",
      category: "Thai",
      price: 13.99,
    },
    {
      id: 11,
      name: "Gyros",
      category: "Greek",
      price: 9.49,
    },
    {
      id: 12,
      name: "Kimchi Fried Rice",
      category: "Korean",
      price: 10.49,
    },
    {
      id: 13,
      name: "Biryani",
      category: "Indian",
      price: 12.99,
    },
    {
      id: 14,
      name: "Ceviche",
      category: "Peruvian",
      price: 14.99,
    },
    {
      id: 15,
      name: "Paella",
      category: "Spanish",
      price: 16.99,
    },
    {
      id: 16,
      name: "Pierogi",
      category: "Polish",
      price: 8.99,
    },
    {
      id: 17,
      name: "Shawarma",
      category: "Middle Eastern",
      price: 11.49,
    },
    {
      id: 18,
      name: "Tandoori Chicken",
      category: "Indian",
      price: 14.49,
    },
    {
      id: 19,
      name: "Pho",
      category: "Vietnamese",
      price: 9.99,
    },
    {
      id: 20,
      name: "Moussaka",
      category: "Greek",
      price: 13.99,
    },
    {
      id: 21,
      name: "Ramen",
      category: "Japanese",
      price: 12.99,
    },
    {
      id: 22,
      name: "Empanadas",
      category: "Latin American",
      price: 8.99,
    },
    {
      id: 23,
      name: "Sauerbraten",
      category: "German",
      price: 15.99,
    },
    {
      id: 24,
      name: "Couscous",
      category: "Moroccan",
      price: 10.99,
    },
    {
      id: 25,
      name: "Goulash",
      category: "Hungarian",
      price: 11.99,
    },
    {
      id: 26,
      name: "Arancini",
      category: "Italian",
      price: 9.99,
    },
    {
      id: 27,
      name: "Poutine",
      category: "Canadian",
      price: 8.99,
    },
    {
      id: 28,
      name: "Cobb Salad",
      category: "American",
      price: 7.99,
    },
    {
      id: 29,
      name: "Pierogi",
      category: "Polish",
      price: 8.99,
    },
    {
      id: 30,
      name: "Fajitas",
      category: "Mexican",
      price: 12.99,
    },
    {
      id: 31,
      name: "Tom Yum Soup",
      category: "Thai",
      price: 10.99,
    },
    {
      id: 32,
      name: "Beef Stroganoff",
      category: "Russian",
      price: 14.99,
    },
    {
      id: 33,
      name: "Falafel Wrap",
      category: "Middle Eastern",
      price: 8.49,
    },
    {
      id: 34,
      name: "Jollof Rice",
      category: "West African",
      price: 9.99,
    },
    {
      id: 35,
      name: "Chimichurri Steak",
      category: "Argentinian",
      price: 17.99,
    },
    {
      id: 36,
      name: "Bánh Mì",
      category: "Vietnamese",
      price: 11.49,
    },
    {
      id: 37,
      name: "Dolma",
      category: "Middle Eastern",
      price: 9.99,
    },
    {
      id: 38,
      name: "Köttbullar",
      category: "Swedish",
      price: 13.99,
    },
    {
      id: 39,
      name: "Fish and Chips",
      category: "British",
      price: 14.49,
    },
    {
      id: 40,
      name: "Rendang",
      category: "Indonesian",
      price: 16.99,
    },
  ],
};
